title: Penghao Liu's Academic CV
page-top-title: Penghao Liu|刘芃昊
top-section-bg-text: Neuosurgery/Neuroscience
home-subtitle: Penghao Liu&ensp;|&ensp;刘芃昊
copyright-text: '&copy; Penghao Liu 2026. All Rights Reserved.'
